"""
prepare_data.py — turn the single hand-labelled set in `rasmlar/` into the two
training datasets the project needs, from one source of truth.

Source (already exists):
    rasmlar/images/*.jpg                      352 frames
    rasmlar/labels/*.txt                      YOLO boxes, classes 0=kamar_bor, 1=kamar_yoq
    rasmlar/labels/classes.txt                ["kamar_bor", "kamar_yoq"]

Produces:
    data/yolo/{train,val}/{images,labels}/    Task 2: 2-class YOLO detector
    data/yolo/data.yaml                        Ultralytics dataset config
    data/classifier/{train,val}/{kamar_bor,kamar_yoq}/*.jpg   Task 3: per-driver crops

Design notes (see CLAUDE.md §4.2):
- YOLO keeps both classes as-is (0=kamar_bor, 1=kamar_yoq).
- Classifier crops each box out of the full frame, padded a little, sorted by class.
- Split is at the FRAME level (a frame's boxes never straddle train/val) so the
  classifier never sees a crop from a frame YOLO trained on. 80/20, seeded.
- The 6 empty label files (no judgeable driver) stay in the YOLO set as background
  negatives but contribute no classifier crops.

Run:
    python tools/prepare_data.py            # from seatbelt_detector/
    python tools/prepare_data.py --crop-pad 0.15 --val-frac 0.2 --seed 42
"""
from __future__ import annotations

import argparse
import random
import shutil
from collections import Counter
from pathlib import Path

import cv2

# Repo layout: this file is seatbelt_detector/tools/prepare_data.py
REPO = Path(__file__).resolve().parents[1]          # .../seatbelt_detector
PROJECT = REPO.parent                                # .../uzinfocom
SRC_IMAGES = PROJECT / "rasmlar" / "images"
SRC_LABELS = PROJECT / "rasmlar" / "labels"

CLASS_NAMES = ["kamar_bor", "kamar_yoq"]             # index == YOLO class id


def read_boxes(label_path: Path) -> list[tuple[int, float, float, float, float]]:
    """Parse a YOLO label file -> list of (cls, xc, yc, w, h) normalised."""
    if not label_path.exists():
        return []
    boxes = []
    for line in label_path.read_text().splitlines():
        parts = line.split()
        if len(parts) != 5:
            continue
        cls, xc, yc, w, h = parts
        boxes.append((int(cls), float(xc), float(yc), float(w), float(h)))
    return boxes


def frame_stems() -> list[str]:
    """Image stems that have a matching label file (incl. empty labels)."""
    stems = []
    for img in sorted(SRC_IMAGES.glob("*.jpg")):
        if (SRC_LABELS / f"{img.stem}.txt").exists():
            stems.append(img.stem)
        else:
            print(f"  [warn] no label for {img.name}, skipping")
    return stems


def stratified_split(stems: list[str], val_frac: float, seed: int):
    """Split frames into train/val. Stratify by whether a frame contains any
    kamar_bor box, so the rare positive class is represented in both splits."""
    rng = random.Random(seed)
    with_pos, without_pos = [], []
    for s in stems:
        classes = {b[0] for b in read_boxes(SRC_LABELS / f"{s}.txt")}
        (with_pos if 0 in classes else without_pos).append(s)

    def take(group):
        rng.shuffle(group)
        n_val = max(1, round(len(group) * val_frac)) if group else 0
        return group[n_val:], group[:n_val]

    tr_p, va_p = take(with_pos)
    tr_n, va_n = take(without_pos)
    train, val = tr_p + tr_n, va_p + va_n
    rng.shuffle(train)
    rng.shuffle(val)
    return train, val


def build_yolo(train: list[str], val: list[str], out: Path):
    for split, stems in [("train", train), ("val", val)]:
        (out / split / "images").mkdir(parents=True, exist_ok=True)
        (out / split / "labels").mkdir(parents=True, exist_ok=True)
        for s in stems:
            shutil.copy2(SRC_IMAGES / f"{s}.jpg", out / split / "images" / f"{s}.jpg")
            shutil.copy2(SRC_LABELS / f"{s}.txt", out / split / "labels" / f"{s}.txt")

    yaml = (
        f"# Auto-generated by tools/prepare_data.py — do not edit by hand.\n"
        f"path: {out.resolve().as_posix()}\n"
        f"train: train/images\n"
        f"val: val/images\n"
        f"nc: {len(CLASS_NAMES)}\n"
        f"names: {CLASS_NAMES}\n"
    )
    (out / "data.yaml").write_text(yaml)
    # also drop a copy where the PDF skeleton expects it: data/data.yaml
    (REPO / "data" / "data.yaml").write_text(yaml)


def build_classifier(train: list[str], val: list[str], out: Path, pad: float):
    counts = {"train": Counter(), "val": Counter()}
    for split, stems in [("train", train), ("val", val)]:
        for name in CLASS_NAMES:
            (out / split / name).mkdir(parents=True, exist_ok=True)
        for s in stems:
            boxes = read_boxes(SRC_LABELS / f"{s}.txt")
            if not boxes:
                continue
            img = cv2.imread(str(SRC_IMAGES / f"{s}.jpg"))
            if img is None:
                print(f"  [warn] cannot read image {s}.jpg")
                continue
            H, W = img.shape[:2]
            for i, (cls, xc, yc, bw, bh) in enumerate(boxes):
                # to pixel xyxy, with padding, clamped to frame
                px, py = xc * W, yc * H
                pw, ph = bw * W * (1 + pad), bh * H * (1 + pad)
                x1 = max(0, int(px - pw / 2)); y1 = max(0, int(py - ph / 2))
                x2 = min(W, int(px + pw / 2)); y2 = min(H, int(py + ph / 2))
                if x2 - x1 < 4 or y2 - y1 < 4:
                    continue
                crop = img[y1:y2, x1:x2]
                name = CLASS_NAMES[cls]
                cv2.imwrite(str(out / split / name / f"{s}__{i}.jpg"), crop)
                counts[split][name] += 1
    return counts


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--val-frac", type=float, default=0.2)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--crop-pad", type=float, default=0.15,
                    help="fractional padding added around each box before cropping")
    args = ap.parse_args()

    assert SRC_IMAGES.exists(), f"missing {SRC_IMAGES}"
    assert SRC_LABELS.exists(), f"missing {SRC_LABELS}"

    stems = frame_stems()
    print(f"Frames with labels: {len(stems)}")

    # overall box stats
    box_counter = Counter()
    empty = 0
    for s in stems:
        b = read_boxes(SRC_LABELS / f"{s}.txt")
        if not b:
            empty += 1
        for cls, *_ in b:
            box_counter[CLASS_NAMES[cls]] += 1
    print(f"Boxes total: {sum(box_counter.values())}  {dict(box_counter)}")
    print(f"Empty (background) frames: {empty}")

    train, val = stratified_split(stems, args.val_frac, args.seed)
    print(f"Split -> train {len(train)} frames | val {len(val)} frames")

    yolo_out = REPO / "data" / "yolo"
    clf_out = REPO / "data" / "classifier"
    for p in (yolo_out, clf_out):
        if p.exists():
            shutil.rmtree(p)

    build_yolo(train, val, yolo_out)
    print(f"YOLO set written -> {yolo_out}")

    counts = build_classifier(train, val, clf_out, args.crop_pad)
    print(f"Classifier crops -> {clf_out}")
    for split in ("train", "val"):
        print(f"  {split}: {dict(counts[split])}")


if __name__ == "__main__":
    main()
